apiVersion: 1

datasources:
  - name: PySpart PostgreSQL KPIs
    uid: pyspart-postgres-kpi
    type: postgres
    access: proxy
    url: postgres:5432
    user: ${GRAFANA_POSTGRES_USER}
    secureJsonData:
      password: ${GRAFANA_POSTGRES_PASSWORD}
    jsonData:
      database: ${GRAFANA_POSTGRES_DB}
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
